const PROXY = process.env.PROXY || 'http://localhost:5000/api';

const signUpRequestsOptions = [
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'abdulimtiaz',
            password: 'budcodeisawesome',
            email: 'abdulimtiaz98@gmail.com',
            firstName: 'Abdul',
            lastName: 'Imtiaz',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'anvinhtr',
            password: 'budcodeisawesome',
            email: 'anvinhtr@gmail.com',
            firstName: 'Anvinh',
            lastName: 'Truong',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'saif',
            password: 'budcodeisawesome',
            email: 'nysaifulislam@gmail.com',
            firstName: 'Saiful',
            lastName: 'Islam',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'tufayelahmed',
            password: 'budcodeisawesome',
            email: 'tufayel5@gmail.com',
            firstName: 'Tufayel',
            lastName: 'Ahmed',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'joybiswas',
            password: 'sylicaisawesome',
            email: 'jbiswas002@citymail.cuny.edu',
            firstName: 'Joy',
            lastName: 'Biswas',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'mehedishohag',
            password: 'sylicaisawesome',
            email: 'mshohag000@citymail.cuny.edu',
            firstName: 'Mehedi',
            lastName: 'Shohag',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'zealptl',
            password: 'sylicaisawesome',
            email: 'zpatel001@citymail.cuny.edu',
            firstName: 'Zeal',
            lastName: 'Patel',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'justinsiu',
            password: 'organicelol',
            email: 'justinsiu1@gmail.com',
            firstName: 'Justin',
            lastName: 'Siu',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'mdrislam30',
            password: 'organicelol',
            email: 'mdrislam30@gmail.com',
            firstName: 'Md',
            lastName: 'Islam',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'refatmonjur',
            password: 'organicelol',
            email: 'refat@refatmonjur.com',
            firstName: 'Refat',
            lastName: 'Monjur',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'tanviryouhana',
            password: 'organicelol',
            email: 'tanviryouhana@gmail.com',
            firstName: 'Tanvir',
            lastName: 'Youhana',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'akbarhaider',
            password: 'collegefulbarisawesome',
            email: 'akbarhaider34@gmail.com',
            firstName: 'Akbar',
            lastName: 'Haider',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'tanzilbaraskar',
            password: 'neuralnetworksarecool',
            email: 'tbaraskar191999@gmail.com',
            firstName: 'Tanzil',
            lastName: 'Baraskar',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'johndoe',
            password: 'johndoe',
            email: 'johndoe@gmail.com',
            firstName: 'John',
            lastName: 'Doe',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'janedoe',
            password: 'janedoe',
            email: 'janedoe@gmail.com',
            firstName: 'Jane',
            lastName: 'Doe',
            gender: 'Female',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'bob',
            password: 'cat',
            email: 'bob@gmail.com',
            firstName: 'Bob',
            lastName: 'Johnson',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'techlead',
            password: 'exgoogleexfb',
            email: 'techlead@gmail.com',
            firstName: 'Patrick',
            lastName: 'Shyu',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'joma',
            password: 'jomatech',
            email: 'joma@joma.com',
            firstName: 'Joma',
            lastName: 'Oppa',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'frankniu',
            password: 'retireearly',
            email: 'niuxiaofei44@gmail.com',
            firstName: 'Frank',
            lastName: 'Niu',
            gender: 'Male',
        },
    },
    {
        method: 'POST',
        url: `${PROXY}/auth/signup`,
        headers: { 'Content-Type': 'application/json' },
        data: {
            username: 'patrick',
            password: 'mayonnaise',
            email: 'patrickstar@gmail.com',
            firstName: 'Patrick',
            lastName: 'Star',
            gender: 'Male',
        },
    },
];

module.exports = signUpRequestsOptions;
