// Mock data for users stored separately
// Information for ~20 users

const usersInfos = [
    {
        username: 'abdulimtiaz',
        password: 'budcodeisawesome',
        first_name: 'Abdul',
        last_name: 'Imtiaz',
        email: 'abdulimtiaz98@gmail.com',
        bio: "I'm a dedicated student looking for full-stack projects to work on with others!",
        occupation: 'Student',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/abdulimtiaz',
            },
            {
                type: 'LinkedIn',
                link: 'https://www.linkedin.com/in/abdul-imtiaz/',
            },
        ],
        interests: [
            'web development',
            'full-stack development',
            'computer architecture',
        ],
        skills: [
            'Javascript',
            'Node',
            'Express',
            'PostgreSQL',
            'Python',
            'VHDL',
            'ASM',
        ],
    },
    {
        username: 'anvinhtr',
        password: 'budcodeisawesome',
        first_name: 'Anvinh',
        last_name: 'Truong',
        email: 'anvinhtr@gmail.com',
        bio: 'Student currently working on my own project called BudCode, check it out!',
        occupation: 'Student',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/anvinhtr',
            },
        ],
        interests: ['web development', 'frontend development'],
        skills: ['HTML', 'CSS', 'Javascript', 'React'],
    },
    {
        username: 'saif',
        password: 'budcodeisawesome',
        first_name: 'Saiful',
        last_name: 'Islam',
        email: 'nysaifulislam@gmail.com',
        bio: 'Computer Science student at The City College of New York. Currently looking for full-time positions. Check out my projects below!',
        occupation: 'Student',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/saifulislamdev',
            },
            {
                type: 'LinkedIn',
                link: 'https://www.linkedin.com/in/saiful-islam-tech/',
            },
        ],
        interests: ['web development', 'full-stack development'],
        skills: [
            'HTML',
            'CSS',
            'Javascript',
            'React',
            'Node',
            'Express',
            'PostgreSQL',
            'Python',
            'Java',
            'C',
            'C++',
            'Git',
            'Visual Studio Code',
        ],
    },
    {
        username: 'tufayelahmed',
        password: 'budcodeisawesome',
        first_name: 'Tufayel',
        last_name: 'Ahmed',
        email: 'tufayel5@gmail.com',
        bio: 'I have multiple full-stack projects under my belt. Open to joining new projects! Feel free to contact me below.',
        occupation: 'Student',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/tufayel5',
            },
            {
                type: 'LinkedIn',
                link: 'https://www.linkedin.com/in/tufayel-ahmed/',
            },
        ],
        interests: ['web development', 'full-stack development'],
        skills: ['HTML', 'CSS', 'Javascript', 'React', 'Visual Studio Code'],
    },
    {
        username: 'joybiswas',
        password: 'sylicaisawesome',
        first_name: 'Joy',
        last_name: 'Biswas',
        email: 'jbiswas002@citymail.cuny.edu',
        occupation: 'Software Engineer',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/joybiswas704',
            },
        ],
        interests: ['web development', 'frontend development'],
        skills: ['HTML', 'CSS', 'Javascript', 'React'],
    },
    {
        username: 'mehedishohag',
        password: 'sylicaisawesome',
        first_name: 'Mehedi',
        last_name: 'Shohag',
        email: 'mshohag000@citymail.cuny.edu',
        bio: 'I love MongoDB',
        occupation: 'Student',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/Mhshohag2256',
            },
        ],
        interests: [
            'web development',
            'frontend development',
            'backend development',
            'full-stack development',
        ],
        skills: [
            'HTML',
            'CSS',
            'Javascript',
            'React',
            'Node',
            'Express',
            'MongoDB',
        ],
    },
    {
        username: 'zealptl',
        password: 'sylicaisawesome',
        first_name: 'Zeal',
        last_name: 'Patel',
        email: 'zpatel001@citymail.cuny.edu',
        bio: 'I enjoy creating designs, but backend development is my true calling',
        occupation: 'Software Engineer',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/zealptl',
            },
        ],
        interests: [
            'web development',
            'frontend development',
            'backend development',
            'full-stack development',
        ],
        skills: [
            'HTML',
            'CSS',
            'Javascript',
            'React',
            'Node',
            'Express',
            'MongoDB',
        ],
    },
    {
        username: 'justinsiu',
        password: 'organicelol',
        first_name: 'Justin',
        last_name: 'Siu',
        email: 'justinsiu1@gmail.com',
        occupation: 'Student',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/JustinSiu00',
            },
        ],
        interests: ['frontend development'],
        skills: ['HTML', 'CSS', 'Javascript', 'React'],
    },
    {
        username: 'mdrislam30',
        password: 'organicelol',
        first_name: 'Md',
        last_name: 'Islam',
        email: 'mdrislam30@gmail.com',
        bio: 'Currently working on Organice. Open to full-time positions!',
        occupation: 'Student',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/mdrislam30',
            },
        ],
        interests: [
            'web development',
            'frontend development',
            'backend development',
            'full-stack development',
        ],
        skills: [
            'HTML',
            'CSS',
            'Javascript',
            'React',
            'Node',
            'Express',
            'MySQL',
        ],
    },
    {
        username: 'refatmonjur',
        password: 'organicelol',
        first_name: 'Refat',
        last_name: 'Monjur',
        email: 'refat@refatmonjur.com',
        bio: 'Open to full-time positions!',
        occupation: 'Student',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/refatmonjur',
            },
        ],
        interests: ['web development'],
        skills: ['HTML', 'CSS', 'Javascript'],
    },
    {
        username: 'tanviryouhana',
        password: 'organicelol',
        first_name: 'Tanvir',
        last_name: 'Youhana',
        email: 'tanviryouhana@gmail.com',
        bio: 'The coolest guy you will ever know!',
        occupation: 'Student',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/Tanvir-Youhana',
            },
        ],
        interests: ['web development', 'networking', 'architecture'],
        skills: [
            'HTML',
            'CSS',
            'Javascript',
            'React',
            'Firebase',
            'VHDL',
            'ASM',
        ],
    },
    {
        username: 'akbarhaider',
        password: 'collegefulbarisawesome',
        first_name: 'Akbar',
        last_name: 'Haider',
        email: 'akbarhaider34@gmail.com',
        bio: 'Software Engineer by day, driven student by night',
        occupation: 'Software Engineer',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/ahaider004',
            },
        ],
        interests: ['web development'],
        skills: ['HTML', 'CSS', 'Javascript'],
    },
    {
        username: 'tanzilbaraskar',
        password: 'neuralnetworksarecool',
        first_name: 'Tanzil',
        last_name: 'Baraskar',
        email: 'tbaraskar191999@gmail.com',
        bio: 'Currently studying Computer Science at The City College of New York. Open to full-time positions!',
        occupation: 'Student',
        gender: 'Male',
        links: [
            {
                type: 'GitHub',
                link: 'https://github.com/tanzil7',
            },
        ],
        skills: ['Python', 'Java'],
    },
    {
        username: 'johndoe',
        password: 'johndoe',
        first_name: 'John',
        last_name: 'Doe',
        email: 'johndoe@gmail.com',
        bio: 'Computer Science student at MIT. Python fanatic!',
        occupation: 'Student',
        gender: 'Male',
        interests: [
            'blockchain',
            'artificial intelligence',
            'machine learning',
        ],
        skills: ['Python'],
    },
    {
        username: 'janedoe',
        password: 'janedoe',
        first_name: 'Jane',
        last_name: 'Doe',
        email: 'janedoe@gmail.com',
        bio: 'Computer Science student at Harvard. Javascript fanatic!',
        occupation: 'Student',
        gender: 'Female',
        interests: [
            'web development',
            'game development',
            'artificial intelligence',
            'machine learning',
        ],
        skills: ['Javascript'],
    },
    {
        username: 'bob',
        password: 'cat',
        first_name: 'Bob',
        last_name: 'Johnson',
        email: 'bob@gmail.com',
        bio: "Hi, I'm Bob! Currently trying to make a shift in my career to software engineering!",
        occupation: 'Student',
        gender: 'Male',
        interests: [
            'web development',
            'game development',
            'artificial intelligence',
            'machine learning',
        ],
        skills: ['HTML', 'CSS', 'Javascript', 'Python'],
    },
    {
        username: 'techlead',
        password: 'exgoogleexfb',
        first_name: 'Patrick',
        last_name: 'Shyu',
        email: 'techlead@gmail.com',
        bio: 'Ex-Google Ex-Facebook TechLead here',
        occupation: 'Retired',
        gender: 'Male',
        links: [
            {
                type: 'YouTube',
                link: 'https://www.youtube.com/c/TechLead',
            },
            {
                type: 'GitHub',
                link: 'https://github.com/techleadhd',
            },
            {
                type: 'LinkedIn',
                link: 'https://www.linkedin.com/in/techleadhd',
            },
        ],
        interests: ['web development', 'mobile development', 'crypto'],
        skills: ['Linux', 'Apache', 'MySQL', 'PHP'],
    },
    {
        username: 'joma',
        password: 'jomatech',
        first_name: 'Joma',
        last_name: 'Oppa',
        email: 'joma@joma.com',
        bio: 'Blindr is the future',
        occupation: 'Content Creator',
        gender: 'Male',
        links: [
            {
                type: 'YouTube',
                link: 'https://www.youtube.com/c/JomaOppa',
            },
        ],
        interests: ['data science'],
        skills: ['Python'],
    },
    {
        username: 'frankniu',
        password: 'retireearly',
        first_name: 'Frank',
        last_name: 'Niu',
        email: 'niuxiaofei44@gmail.com',
        bio: 'Retired Software Engineer, now a TikToker!',
        occupation: 'Content Creator',
        gender: 'Male',
        interests: ['web development'],
        skills: ['HTML', 'CSS', 'Javascript'],
    },
    {
        username: 'patrick',
        password: 'mayonnaise',
        first_name: 'Patrick',
        last_name: 'Star',
        email: 'patrickstar@gmail.com',
        gender: 'Male',
    },
];

module.exports = usersInfos;
